auto:           true
baseurl:        "/"
permalink:      "/:categories/:title/"
paginate:       1000
pygments:       true
lsi:            false
owner-name:     "Sean Kealey"
owner-page:     "http://www.seankealey.net/"
owner-email:    "sean.kealey@gmail.com"
plugins:        "./_plugins"
topic_list:     ["categories"]
name:           "Template"
static_url:     ""
domain:         localhost
port:           4000
exclude: [grid.less, mixins.less, reset.less, styles.less, variables.less]